import london from "../assets/Images/subcategory/london.svg";
import birmingham from "../assets/Images/subcategory/brimingham.svg";
import liverpool from "../assets/Images/subcategory/liverpool.svg";
export const POPULAR_CITIES_LEVERL_THREE = [
  { id: 1, city_image: london, city_name: "London" },
  { id: 2, city_image: birmingham, city_name: "Birmingham" },
  { id: 3, city_image: liverpool, city_name: "Liverpool" },
  // { id: 4, city_image: london, city_name: "Chester" },
  // { id: 5, city_image: london, city_name: "Warrington" },
  // { id: 6, city_image: london, city_name: "Ellesmere Port" },
  // { id: 7, city_image: london, city_name: "Nantwich" },
  // { id: 8, city_image: london, city_name: "Winsford" },
  // { id: 9, city_image: london, city_name: "Neston" },
  // { id: 10, city_image: london, city_name: "Runcorn" },
  // { id: 11, city_image: london, city_name: "Frodsham" },
  // { id: 12, city_image: birmingham, city_name: "Bolton" },
  // { id: 13, city_image: birmingham, city_name: "Wythenshawe" },
  // { id: 14, city_image: birmingham, city_name: "Wigan" },
  // { id: 15, city_image: birmingham, city_name: "Stockport" },
  // { id: 16, city_image: birmingham, city_name: "Oldham" },
  // { id: 17, city_image: birmingham, city_name: "Rochdale" },
  // { id: 18, city_image: birmingham, city_name: "Salford" },
  // { id: 19, city_image: birmingham, city_name: "Bury" },
  // { id: 20, city_image: birmingham, city_name: "Sale" },
  // { id: 21, city_image: liverpool, city_name: "Skelmersdale" },
  // { id: 22, city_image: liverpool, city_name: "Ormskirk" },
  // { id: 23, city_image: liverpool, city_name: "Birkenhead" },
  // { id: 24, city_image: liverpool, city_name: "St Helens" },
  // { id: 25, city_image: liverpool, city_name: "Southport" },
  // { id: 26, city_image: liverpool, city_name: "Bebington" },
  // { id: 27, city_image: liverpool, city_name: "Bootle" },
  // { id: 28, city_image: liverpool, city_name: "Crosby" },
  // { id: 29, city_image: liverpool, city_name: "Huyton" },
  // { id: 30, city_image: liverpool, city_name: "Prescot" },
  // { id: 31, city_image: liverpool, city_name: "Formby" }
];
